// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhfnedhqltgjrmpobgpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoZm5lZGhxbHRnanJtcG9iZ3BwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MjU3ODUsImV4cCI6MjA2NzMwMTc4NX0.Ns32LOmZFah5kLNlkSbkd-v7no4RzGaZfR358ttmssI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});